x-postgres-common:
  &postgres-common
  image: postgres:16.3
  user: postgres
  restart: always
  healthcheck:
    test: 'pg_isready -U postgres --dbname=${DATABASE_NAME}'
    interval: 10s
    timeout: 5s
    retries: 5

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:8080
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

  db:
    <<: *postgres-common
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/00_init.sql
      - db-master-data:/var/lib/postgresql/data

volumes:
  db-master-data: