server:
  port: 8080

spring:
  application:
    name: ITMO-TEST-TASK
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:itmo_db}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

flyway:
  enabled: true
  baseline-on-migrate: true
  locations: classpath:db/migration